version: "3.3"

services:
  microgateway:
    image: microgateway
    depends_on:
      - redis
    ports:
      - "8080:8080"
    networks:
      - webnet

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - webnet

networks:
    webnet:
