version: "3.3"

services:
  gotway:
    image: gotwaygateway/gotway
    depends_on:
      - redis
    environment: 
      - GOTWAY_SERVICE_PORT=8000
      - ENV=production
      - DATABASE=redis
      - REDIS_SERVER=redis:6379 
      - HEALTH_CHECK_INTERVAL_SECONDS=10
      - HEALTH_CHECK_TIMEOUT_SECONDS=5
      - TLS=true
      - TLS_CERT=/etc/ssl/server.pem
      - TLS_KEY=/etc/ssl/server.key
    ports:
      - "8000:8000"
    volumes:
      - "./cert:/etc/ssl"