version: "3.3"

services:
  redis:
    image: redis:6.2.4-alpine3.13
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  gotway:
    image: gotwaygateway/gotway
    depends_on:
      - redis
    environment: 
      - GOTWAY_SERVICE_PORT=11000
      - ENV=production
      - REDIS_SERVER=redis:6379 
      - HEALTH_CHECK_INTERVAL_SECONDS=10
      - HEALTH_CHECK_TIMEOUT_SECONDS=5
      - TLS=true
      - TLS_CERT=/etc/ssl/server.pem
      - TLS_KEY=/etc/ssl/server.key
    ports:
      - "11000:11000"
    volumes:
      - "./cert:/etc/ssl"