nameOverride: ""
fullnameOverride: ""

image:
  repository: gotwaygateway/gotway
  pullPolicy: IfNotPresent
  tag: "0.0.1"

service:
  type: NodePort
  interalPort: 443
  externalPort: 31000

tlsEnabled: true

livenessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 15
    
readinessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 3
  periodSeconds: 15

ingressRoute:
  enabled: true
  host: api.gotway.duckdns.org
  entryPoints:
    - websecure

env: production

databaseType: redis

redisConfig:
  address: gotway-redis-master:6379
  db: 0

healthCheck:
  intervalSeconds: 10
  timeoutSeconds: 5

resources: {}

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

nodeSelector: {}


serviceExamples:
  enabled: true

  catalog:
    image:
      repository: gotwaygateway/catalog
      pullPolicy: IfNotPresent
      tag: "v0.0.1"

    service:
      type: ClusterIP
      port: 80

  route:
    image:
      repository: gotwaygateway/route
      pullPolicy: IfNotPresent
      tag: "v0.0.1"

    service:
      type: ClusterIP
      port: 80

  stock:

# dependencies

redis:
  cluster:
    enabled: false
  usePassword: false