apiVersion: v1
kind: Service
metadata:
  name: route
  namespace: gotway
  labels:
    app: route
    tier: back
spec:
  selector:
    app: route
    tier: back
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: route
  namespace: gotway
  labels:
    app: route
    tier: back
spec:
  selector:
    matchLabels:
      app: route
      tier: back
  template:
    metadata:
      labels:
        app: route
        tier: back
    spec:
      containers:
        - name: route
          image: gotway/route:0.0.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: service-port
              containerPort: 80
