apiVersion: v1
kind: Service
metadata:
  name: microgateway
  namespace: microgateway
  labels:
    app: microgateway
    tier: api-gateway
spec:
  selector:
    app: microgateway
    tier: api-gateway
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microgateway
  namespace: microgateway
  labels:
    app: microgateway
    tier: api-gateway
spec:
  selector:
    matchLabels:
      app: microgateway
      tier: api-gateway
  template:
    metadata:
      labels:
        app: microgateway
        tier: api-gateway
    spec:
      containers:
        - name: microgateway
          image: gosmogolang/microgateway:0.0.1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: service-port
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/health
              port: service-port
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 15
          envFrom:
            - configMapRef:
                name: microgateway
