apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-gotway
  namespace: gotway
  labels:
    app: gotway
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-gotway
  namespace: gotway
  labels:
    app: gotway
    tier: database
spec:
  selector:
    app: gotway
    tier: database
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-gotway
  namespace: gotway
  labels:
    app: gotway
    tier: database
spec:
  selector:
    matchLabels:
      app: gotway
      tier: database
  template:
    metadata:
      labels:
        app: gotway
        tier: database
    spec:
      containers:
        - name: redis-gotway
          image: redis
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 75m
            limits:
              memory: 64Mi
              cpu: 125m
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: redis-gotway
